### PR TITLE
Vault Support and Cleanup

### PR DESCRIPTION
**Pull request by CodeTheDev**
- Added basic Vault support into the plugin to display proper prefixes and suffixes of users.
- Removed unused imports found in some classes (ChatItem.java).
- Fixed some deprecation issues (PlayerChatEventListener.java). Other deprecation issues cannot currently be fixed without a rewrite.
- Rewrote ChatItemCommand.java to look nicer/cleaner when displaying command output to users.
- Fixed some issues in pom.xml involving the Spigot repository and config.yml not being included in the final jar.
- Updated README.md to better reflect name and description as found in the plugin files.
- Updated plugin.yml to include Vault as a soft-dependency.

### CODE REVIEW

**Comment by Sven65** [comment]
Sorry, I didn't see your PR until now! As it stands right now, I changed the way I'm doing support for other plugins by moving the event priority of `PlayerChatEventListener#onPlayerChat` in order to better support other chat plugins as well.

I'm unsure how to go forward with the pull request, and I'd like some input from you as well.

**Comment by CodeTheDev** [comment]
Ah, I see! I was not aware you were working on this. I've tested the new version and it seems to be working quite nicely with Vault chat formatting, so I will close this pull request.

Cheers,

Code

**Comment by Sven65** [comment]
No worries! Thanks for taking the time to submit the pull request!

**Comment by CodeTheDev** [comment]
Any time! I'm glad someone is making a version of this for 1.16!

**Pull request closed without merging**
